openapi: 3.0.3
info:
  title: Titanium Porcupine
  description: Description
  version: 1.0.0
servers:
  - url: http://192.168.1.2:5080

paths:
  /auth/login:
    post:
      operationId: login
#      tags:
#        - auth
      requestBody:
        content:
          application/json:
            schema:
              type:
                object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          $ref: '#/components/responses/SuccessfulAuthentication'
  /auth/accounts:
    post:
      operationId: createAccount
#      tags:
#        - auth
      requestBody:
        content:
          application/json:
            schema:
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - firstName
                - lastName
                - email
                - password
      responses:
        200:
          $ref: '#/components/responses/SuccessfulAuthentication'
components:
  schemas:
    Ticket:
      properties:
        id:
          type: string
        qrCode:
          type: string
        type:
          type: string
          enum:
            - transport
            - event
        validFrom:
          type: string
        validUntil:
          type: string
      required:
        - id
        - type
        - qrCode
        - validFrom
        - validUntil
  responses:
    SuccessfulAuthentication:
      description: Successful registration
      content:
        application/json:
          schema:
            type: object
            properties:
              accessToken:
                type: string
                description: Access token
              refreshToken:
                type: string
                description: Refresh token
            required:
              - accessToken
              - refreshToken
