export enum SCREENS {
    LOGIN = "LOGIN",
    CREATE_ACCOUNT = "CREATE_ACCOUNT",
    HOME = "HOME",
    PUBLIC_TRANSPORT = "PUBLIC_TRANSPORT",
    BUY_PUBLIC_TRANSPORT_TICKET = "BUY_PUBLIC_TRANSPORT_TICKET",
    EVENTS = "EVENTS",
    MAP = "MAP",
    RANDOM_EXPERIENCE = "RANDOM_EXPERIENCE",
    TICKETS = "TICKETS",
    DISCOVER = "DISCOVER",
    SETTINGS = "SETTINGS",
    ADD_CREDIT_CARD = "ADD_CREDIT_CARD"
}
